FROM eclipse-temurin:21-jre

WORKDIR /app

COPY target/nexia-core-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8081

ENV DB_HOST=db
ENV DB_PORT=5432
ENV DB_NAME=nexia
ENV DB_USER=nexia
ENV DB_PASSWORD=nexia

ENTRYPOINT ["java","-jar","/app/app.jar"]
